---
apiVersion: v1
kind: Secret
metadata:
  name: test8-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/test8-gitops.git
